import type { Api, Model } from "@earendil-works/pi-ai/compat";

/**
 * New models missing from pi-ai 0.82.1. Metadata follows pi-ai 0.85.1 and the
 * provider catalogs; keep the existing adapters and catalog until a full upgrade.
 * Native registry entries take precedence when pi-ai is updated.
 */
export const ADDITIONAL_MODELS: Record<string, Model<Api>> = {
  "anthropic:claude-fable-5-1": {
    id: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    api: "anthropic-messages",
    provider: "anthropic",
    baseUrl: "https://api.anthropic.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 0.25,
      cacheWrite: 12.5,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      forceAdaptiveThinking: true,
      supportsStrictTools: true,
      supportsTemperature: false,
    },
    thinkingLevelMap: {
      off: null,
      xhigh: "xhigh",
      max: "max",
    },
  },
  "openai:gpt-6-astra": {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    api: "openai-responses",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 1,
      cacheWrite: 12.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 20,
          output: 75,
          cacheRead: 2,
          cacheWrite: 25,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsStrictMode: true,
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
      supportsExplicitPromptCacheMode: true,
    },
  },
  "codex:gpt-6-astra": {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    api: "openai-codex-responses",
    provider: "openai-codex",
    baseUrl: "https://chatgpt.com/backend-api",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 1,
      cacheWrite: 12.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 20,
          output: 75,
          cacheRead: 2,
          cacheWrite: 25,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: null,
      minimal: "low",
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
    },
  },
  "openrouter:anthropic/claude-fable-5.1": {
    id: "anthropic/claude-fable-5.1",
    name: "Anthropic: Claude Fable 5.1",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 0.25,
      cacheWrite: 12.5,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
      cacheControlFormat: "anthropic",
    },
  },
  "openrouter:openai/gpt-6-astra": {
    id: "openai/gpt-6-astra",
    name: "OpenAI: GPT-6 Astra",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 1,
      cacheWrite: 12.5,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
    },
  },
  "openrouter:google/gemini-3.8-flash": {
    id: "google/gemini-3.8-flash",
    name: "Google: Gemini 3.8 Flash",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: null,
      max: null,
    },
    input: ["text", "image"],
    cost: {
      input: 0.75,
      output: 3.75,
      cacheRead: 0.075,
      cacheWrite: 0.041667,
    },
    contextWindow: 1048576,
    maxTokens: 65536,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
    },
  },
};
